# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort (python)

-   repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
    -   id: flake8

-   repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.10.2
    hooks:
    -   id: cspell
        # Let cspell know about our custom dictionary in pyproject.toml
        args: ["--config", "pyproject.toml"]
        # Exclude the lock file which has many hashes and generated content
        exclude: poetry.lock