[project]
name = "msys2-autobuild"
version = "0.1.0"
description = ""
authors = [
  { name = "Christoph Reiter", email = "reiter.christoph@gmail.com" }
]
requires-python = "~=3.10"
dependencies = [
  "PyGithub>=2.6.0,<3",
  "tabulate>=0.9.0,<0.10",
  "requests>=2.28.1,<3",
  "requests-cache>=1.0.0,<2",
  "urllib3>=2.2.1,<3",
]

[project.scripts]
msys2-autobuild = "msys2_autobuild.main:run"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
mypy = "1.17.0"
flake8 = "^7.0.0"
types-tabulate = "^0.9.0.0"
types-requests = "^2.25.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
